### PR TITLE
Fixes regulation layers color and Lan/Pno alerts

### LINKED ISSUE #1556: [BUG] Quand on fait le preview de la zone depuis la recherche REG, la couleur rouge n'est pas affichée

### LINKED ISSUE #1579: [BUG] Quand il n'y a pas de période de pêche renseignée, les couches REG apparaissent en rouge alors qu'elles devraient être en bleu
Screenshot from 2023-01-27 15-03-02

### LINKED ISSUE #1701: [BUG] Sur un Scheduled dans Rules du `backend`
```
23-01-27 17:58:00.432  INFO .a.r.ExecutePnoAndLanWeightToleranceRule : PNO_LAN_WEIGHT_TOLERANCE: Found 2 catches which are over tolerance for LAN OOF20190627059908 and PNO OOF20191011059902
23-01-27 17:58:00.475  WARN o.h.e.j.s.SqlExceptionHelper             : SQL Error: 0, SQLState: 42883
23-01-27 17:58:00.475 ERROR o.h.e.j.s.SqlExceptionHelper             : ERROR: operator does not exist: uuid = bytea
  Hint: No operator matches the given name and argument types. You might need to add explicit type casts.
  Position: 185
23-01-27 17:58:00.476  INFO o.h.e.i.DefaultLoadEventListener         : HHH000327: Error performing load command

org.hibernate.exception.SQLGrammarException: JDBC exception executing SQL [select a1_0.alert_id,a1_0.creation_date,a1_0.external_reference_number,a1_0.internal_reference_number,a1_0.ircs,a1_0.trip_number,a1_0.value from pno_lan_alerts a1_0 where a1_0.alert_id=?]
	at org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDelegate.java:89)
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:56)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:109)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:95)
	at org.hibernate.sql.results.jdbc.internal.DeferredResultSetAccess.executeQuery(DeferredResultSetAccess.java:253)
	at org.hibernate.sql.results.jdbc.internal.DeferredResultSetAccess.getResultSet(DeferredResultSetAccess.java:146)
	at org.hibernate.sql.results.jdbc.internal.JdbcValuesResultSetImpl.advanceNext(JdbcValuesResultSetImpl.java:205)
	at org.hibernate.sql.results.jdbc.internal.JdbcValuesResultSetImpl.processNext(JdbcValuesResultSetImpl.java:85)
	at org.hibernate.sql.results.jdbc.internal.AbstractJdbcValues.next(AbstractJdbcValues.java:29)
	at org.hibernate.sql.results.internal.RowProcessingStateStandardImpl.next(RowProcessingStateStandardImpl.java:88)
	at org.hibernate.sql.results.spi.ListResultsConsumer.consume(ListResultsConsumer.java:183)
	at org.hibernate.sql.results.spi.ListResultsConsumer.consume(ListResultsConsumer.java:33)
	at org.hibernate.sql.exec.internal.JdbcSelectExecutorStandardImpl.doExecuteQuery(JdbcSelectExecutorStandardImpl.java:443)
	at org.hibernate.sql.exec.internal.JdbcSelectExecutorStandardImpl.executeQuery(JdbcSelectExecutorStandardImpl.java:166)
	at org.hibernate.sql.exec.internal.JdbcSelectExecutorStandardImpl.list(JdbcSelectExecutorStandardImpl.java:91)
	at org.hibernate.sql.exec.spi.JdbcSelectExecutor.list(JdbcSelectExecutor.java:31)
	at org.hibernate.loader.ast.internal.SingleIdLoadPlan.load(SingleIdLoadPlan.java:140)
	at org.hibernate.loader.ast.internal.SingleIdLoadPlan.load(SingleIdLoadPlan.java:110)
	at org.hibernate.loader.ast.internal.SingleIdEntityLoaderStandardImpl.load(SingleIdEntityLoaderStandardImpl.java:72)
	at org.hibernate.persister.entity.AbstractEntityPersister.doLoad(AbstractEntityPersister.java:4401)
	at org.hibernate.persister.entity.AbstractEntityPersister.load(AbstractEntityPersister.java:4391)
	at org.hibernate.event.internal.DefaultLoadEventListener.loadFromDatasource(DefaultLoadEventListener.java:597)
	at org.hibernate.event.internal.DefaultLoadEventListener.doLoad(DefaultLoadEventListener.java:570)
	at org.hibernate.event.internal.DefaultLoadEventListener.load(DefaultLoadEventListener.java:224)
	at org.hibernate.event.internal.DefaultLoadEventListener.proxyOrLoad(DefaultLoadEventListener.java:363)
	at org.hibernate.event.internal.DefaultLoadEventListener.doOnLoad(DefaultLoadEventListener.java:113)
	at org.hibernate.event.internal.DefaultLoadEventListener.onLoad(DefaultLoadEventListener.java:75)
	at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:118)
	at org.hibernate.internal.SessionImpl.fireLoadNoChecks(SessionImpl.java:1244)
	at org.hibernate.internal.SessionImpl.fireLoad(SessionImpl.java:1232)
	at org.hibernate.loader.access.IdentifierLoadAccessImpl.doLoad(IdentifierLoadAccessImpl.java:195)
	at org.hibernate.loader.access.IdentifierLoadAccessImpl.lambda$load$1(IdentifierLoadAccessImpl.java:161)
	at org.hibernate.loader.access.IdentifierLoadAccessImpl.perform(IdentifierLoadAccessImpl.java:108)
	at org.hibernate.loader.access.IdentifierLoadAccessImpl.load(IdentifierLoadAccessImpl.java:161)
	at org.hibernate.internal.SessionImpl.get(SessionImpl.java:1028)
	at org.hibernate.event.internal.DefaultMergeEventListener.lambda$entityIsDetached$0(DefaultMergeEventListener.java:344)
	at org.hibernate.engine.spi.LoadQueryInfluencers.fromInternalFetchProfile(LoadQueryInfluencers.java:79)
	at org.hibernate.event.internal.DefaultMergeEventListener.entityIsDetached(DefaultMergeEventListener.java:342)
	at org.hibernate.event.internal.DefaultMergeEventListener.onMerge(DefaultMergeEventListener.java:178)
	at org.hibernate.event.internal.DefaultMergeEventListener.onMerge(DefaultMergeEventListener.java:81)
	at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:107)
	at org.hibernate.internal.SessionImpl.fireMerge(SessionImpl.java:830)
	at org.hibernate.internal.SessionImpl.merge(SessionImpl.java:816)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.orm.jpa.SharedEntityManagerCreator$SharedEntityManagerInvocationHandler.invoke(SharedEntityManagerCreator.java:307)
	at jdk.proxy3/jdk.proxy3.$Proxy159.merge(Unknown Source)
	at org.springframework.data.jpa.repository.support.SimpleJpaRepository.save(SimpleJpaRepository.java:613)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.data.repository.core.support.RepositoryMethodInvoker$RepositoryFragmentMethodInvoker.lambda$new$0(RepositoryMethodInvoker.java:288)
	at org.springframework.data.repository.core.support.RepositoryMethodInvoker.doInvoke(RepositoryMethodInvoker.java:136)
	at org.springframework.data.repository.core.support.RepositoryMethodInvoker.invoke(RepositoryMethodInvoker.java:120)
	at org.springframework.data.repository.core.support.RepositoryComposition$RepositoryFragments.invoke(RepositoryComposition.java:516)
	at org.springframework.data.repository.core.support.RepositoryComposition.invoke(RepositoryComposition.java:285)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$ImplementationMethodExecutionInterceptor.invoke(RepositoryFactorySupport.java:628)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.doInvoke(QueryExecutorMethodInterceptor.java:168)
	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.invoke(QueryExecutorMethodInterceptor.java:143)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:137)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:163)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.data.repository.core.support.MethodInvocationValidator.invoke(MethodInvocationValidator.java:94)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:218)
	at jdk.proxy3/jdk.proxy3.$Proxy170.save(Unknown Source)
	at fr.gouv.cnsp.monitorfish.infrastructure.database.repositories.JpaPNOAndLANAlertRepository.save(JpaPNOAndLANAlertRepository.kt:18)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:752)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:137)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:752)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:703)
	at fr.gouv.cnsp.monitorfish.infrastructure.database.repositories.JpaPNOAndLANAlertRepository$$SpringCGLIB$$0.save(<generated>)
	at fr.gouv.cnsp.monitorfish.domain.use_cases.alert.rules.ExecutePnoAndLanWeightToleranceRule.execute(ExecutePnoAndLanWeightToleranceRule.kt:58)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:752)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:752)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:703)
	at fr.gouv.cnsp.monitorfish.domain.use_cases.alert.rules.ExecutePnoAndLanWeightToleranceRule$$SpringCGLIB$$0.execute(<generated>)
	at fr.gouv.cnsp.monitorfish.domain.use_cases.alert.ExecuteRules.executeLogbookRules(ExecuteRules.kt:42)
	at fr.gouv.cnsp.monitorfish.domain.use_cases.alert.ExecuteRules.execute(ExecuteRules.kt:31)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.postgresql.util.PSQLException: ERROR: operator does not exist: uuid = bytea
  Hint: No operator matches the given name and argument types. You might need to add explicit type casts.
  Position: 185
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:496)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:413)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:190)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:134)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
	at org.hibernate.sql.results.jdbc.internal.DeferredResultSetAccess.executeQuery(DeferredResultSetAccess.java:217)
	... 117 more

```

### PR DESCRIPTION
**Pull request by louptheron**
## Linked issues

- Resolve #1579
- Resolve #1556 
- Resolve #1701 
- Resove #1692 
- Fix Ktlint linter not running on JDK 16+

----

- [ ] Tests E2E (Cypress)

### CODE REVIEW

File: frontend/src/features/map/layers/RegulatoryPreviewLayer.tsx [hunk 1]
```diff
@@ -54,25 +56,31 @@ function UnmemoizedRegulatoryPreviewLayer({ map }: RegulatoryPreviewLayerProps)
...
-      if (features?.length) {
-        getVectorSource().addFeatures(features)
-        dispatch(zoomInLayer({ feature: features[0] }))
-      }
+    if (!regulatoryZonesToPreview?.length) {
+      return
     }
-  }, [dispatch, map, regulatoryGeometriesToPreview])
+
+    const features = regulatoryZonesToPreview
```
Comment (ivangabriele) [inline frontend/src/features/map/layers/RegulatoryPreviewLayer.tsx:63]: A good practice in components to reduce their internal logic is to export the transformations into a related component file like a `utils.ts`, which also makes these transformations easily testable at the same time.

File: frontend/src/features/map/layers/styles/isForbiddenPeriod.test.ts [hunk 2]
```diff
@@ -551,6 +551,44 @@ describe('isForbiddenPeriod', () => {
     const currentDate = getUtcDayjs().day(1) // Monday
     expect(isForbiddenPeriod(feature, currentDate)).toEqual(true)
   })
+
+  it('isForbiddenPeriod Should return false When authorized is false and dates contains a null item', async () => {
```
Comment (ivangabriele) [inline frontend/src/features/map/layers/styles/isForbiddenPeriod.test.ts:555]: In Jest (but also in Mocha, AVA, etc) we normally don't repeat the name of the function in the `it` since it should already be declared in the `describe`:

```
describe('myFunction()', () => {
  it('should do that',  () => ...)
  it('should also do that',  () => ...)
 })
```

File: frontend/src/features/map/layers/styles/isForbiddenPeriod.ts [hunk 3]
```diff
@@ -8,22 +10,33 @@ import type Feature from 'ol/Feature'
...
+     *
+     * If they are set, the period will be forbidden when
      *  - hasAllowedRange is false AND
      *  - hasAllowedDate is false AND
      *  - hasAllowedWeekDay is false
      */
     case true: {
-      const isAlwaysAuthorized = fishingPeriod.always
+      const isAlwaysAuthorized =
+        removeNullValues(fishingPeriod.dates).length === 0 &&
```
Comment (ivangabriele) [inline frontend/src/features/map/layers/styles/isForbiddenPeriod.ts:33]: I would have made a small global util (i.e.: `isNullishEmpty()`) for that and write it like that:

```tx
const isAlwaysAuthorized = isNullishEmpty([...fishingPeriod.dates, ...fishingPeriod.weekdays, ...fishingPeriod.dateRanges])
```

**Review by ivangabriele — APPROVED** [review]

File: frontend/src/features/map/layers/styles/isForbiddenPeriod.test.ts (hunk 2 above)
Comment (louptheron) [reply frontend/src/features/map/layers/styles/isForbiddenPeriod.test.ts:555]: I'm used to having describe with multiple functions to test, I removed the repeat of the function name

File: frontend/src/features/map/layers/styles/isForbiddenPeriod.ts (hunk 3 above)
Comment (louptheron) [reply frontend/src/features/map/layers/styles/isForbiddenPeriod.ts:33]: If it's used in another part of the app, I'll do it, for the time being I don't think we need an util.

File: frontend/src/domain/entities/logbook.js [hunk 4]
```diff
@@ -348,37 +315,58 @@ export const getTotalFARWeightFromMessages = logbookMessages => {
...
+      weight:  multiplyByConversionFactorIfNeeded(speciesCatch.weight, conversionFactor),
       speciesName: speciesCatch.speciesName,
       totalWeight: totalWeight
     }
   }
 }
 
+function multiplyByConversionFactorIfNeeded (weight, conversionFactor = 1) {
+  if (!weight) {
+    return 0
```
[the remark this answers is not in the document]
Comment (louptheron) [reply frontend/src/domain/entities/logbook.js:362]: We don't wan't to erase weight when the `conversionFactor` is null or undefined, but if the weight is null or undefined then it is as a `0` value
