### PR TITLE
Fix multiple issues in mission list and form

### LINKED ISSUE #1777: Missions - Vue liste des missions
Faire la vue liste des missions. 
Cf écran XD 47

### LINKED ISSUE #1782: Missions – Revue du formulaire (champs mission - colonne 1)
**RETOURS UX**

- [x] Le menu déroulant "ressource 1" doit s'appeler "moyen 1" 👍🏻 
- [x] Permettre de rechercher au clavier dans les menus déroulants des administrations et unités 👍🏻 
- [x] Dégriser le champ "unité" : on doit pouvoir saisir indifféremment l'administration ou l'unité en premier – c'est un retour d'xp côté CACEM, parfois les utilisateurs ne connaissent pas l'admin. de l'unité, donc veulent pouvoir chercher direct dans le menu unité. 👍🏻 
- [x] Il faut que le champ "contact" se dégrise à partir du moment où on a saisi une unité, pas besoin d'avoir saisi un moyen 👍🏻 
- [x] Retirer les champs "objectifs du vol" et "segment ciblé" de la colonne 1 dans le cas d'une mission air => on les a basculé dans l'action de surveillance aérienne (dans la colonne 3) 👍🏻 
- [x] Il y a un "undefined" à retirer dans le bouton "valider" lors de la création/l'édition d'une zone de mission sur la carte 👍🏻 

**RETOURS UI**

- [x] Le bandeau en haut de la fenêtre me semble trop grand. J'ai retouché les écrans, il fait 80 px de haut. 👍🏻 
- [x] Ne pas ancrer "Informations générales", cela doit défiler au scroll avec le reste de la colonne 👍🏻 
- [x] La marge gauche au sein de la colonne doit faire 40 px. 👍🏻 
- [x] Concernant la longueur des champs, j'ai étudié ta proposition Ivan, et je crois que je resterais sur mes écrans ;) je trouve ça plus aéré avec des champs plus courts, qui ne font pas toute la largeur de la colonne. Je les mettrais donc en 384 px de long (ils font 380 sur mes maquettes, mais 384 est un multiple de 8). 👍🏻 
- [x] Dans la même logique que ci-dessus, le bouton "ajouter une zone de mission" doit s'adapter à la longueur des champs (384 px donc), et non aux icônes "éditer" et "supprimer" de la zone de mission 👍🏻 
- [x] Ne pas mettre d'icône de suppression face au champ "administration" de la première unité 👍🏻 
- [ ] Le bouton "ajouter une autre unité" est un small button (il doit donc faire 24 px de haut) et doit faire 161px de long ; il ne s'adapte pas à la longueur des autres champs. **=> ok pour le fait qu'il ne s'adapte pas à la longueur des autres champs**
- [x] Le bouton "centrer sur la carte" du polygone de la zone de mission doit être par défaut en Slate Gray 👍🏻 
- [ ] [Ce point vaut pour tous les boutons du formulaire] Il y a un pb de centrage du texte dans les secondary buttons, le texte apparaît trop haut (cf. capture ci-dessous). Je mets ce point ici et pas dans Monitor UI parce que je n'ai pas l'impression que ça le fasse dans le Storybook. 

image

### LINKED ISSUE #1783: Missions – Revue du formulaire (actions de contrôle - colonne 2)
### **RETOURS UX**

- [x] Les cartes ne se mettent pas à jour quand un navire est renseigné dans le formulaire, ou quand le nb de pistes est renseigné dans les surveillances aériennes. NB : pour la typo, le nom du navire et le nb de pistes survolées doit être en Bold, le reste en Medium (cf. écrans)
- [x] Tags appréhension sur les cartes d'actions de contrôle : lorsque sont cochés dans le formulaire les champs "appréhension engin", "appréhension espèce" ou "appréhension navire", il faut afficher les tags correspondants sur la carte, avec une pastille rouge. Cette info étant importante, on peut mettre ces tags en 1er dans la carte. 👍🏻 
- [x] Tags NATINF sur les cartes d'actions de contrôle : j'ai rectifié les écrans, je pense que c'est plus judicieux de regrouper les n° de NATINF dans un seul tag s'il y en a plusieurs. Cela évite de répéter "NATINF" ce qui prend de la place pour rien. Cf. écrans [27](https://xd.adobe.com/view/0eacf501-00f4-496b-bf08-4e9ca7985909-5bff/screen/0df79652-90da-4d4b-95c2-cbf94dfcfc82) et [28](https://xd.adobe.com/view/0eacf501-00f4-496b-bf08-4e9ca7985909-5bff/screen/2670af42-0209-4624-ac3d-7b00ed514ae3). 👍🏻 

### **RETOURS UI**

- [x] Les cartes des actions doivent faire par défaut 52 px de haut, avant que des tags n'y soient rajoutés selon le contenu des formulaires remplis dans la colonne 3 👍🏻 
- [x] Fonds colorés des cartes : les actions de contrôle doivent être sur fond blanc, les actions de surveillance sur fond Gainsboro et les notes libres sur fond Blue Yonder 25% 👍🏻

### LINKED ISSUE #1925: Missions – Certains contrôles se dupliquent tout seuls
J'avais déjà remarqué ça sur certaines missions avant, mais je ne l'avais pas remonté, pensant que c'était peut-être lié au bug sur l'enregistrement des missions et contrôles.
Il y a un ex. sur la mission du BGMAR Sète - P609 Hérault : 
- j'ai créé ce matin un contrôle sur l'Océane III, j'ai enregistré la mission et ça a dupliqué deux fois le contrôle (et les a daté de la veille, le 17 avril)
- j'ai créé une nouvelle mission, et quand je l'ai enregistrée, j'ai vu qu'il y avait un 4è contrôle sur l'Océane III qui était apparu dans la mission de BGMAR Sète... 
- enfin, j'ai essayé de créer un nouveau contrôle dans la mission de la BGMAR Sète, j'ai renseigné un navire mais il ne s'enregistre pas : l'action de contrôle indique toujours "contrôle à la débarque à renseigner", et quand j'enregistre la mission, ce 5è contrôle n'apparaît pas dans la liste des navires contrôlés.

image

### LINKED ISSUE #1931: Les `mission_action` ne peuvent pas être supprimées
Pour reproduire : 
- supprimer une action dans une mission (l'action disparait)
- cliquer sur "enregistrer"
- sortir de la mission
- revenir dans la mission : l'action est revenue

### PR DESCRIPTION
**Pull request by ivangabriele**
## Linked issues

- #1777
- Resolve #1782
- Resolve #1783
- Resolve #1925
- #1930
- Resolve #1931

----

- [ ] Tests E2E (Cypress)

### CODE REVIEW

File: frontend/src/features/SideWindow/MissionForm/index.tsx [hunk 1]
```diff
@@ -120,14 +122,17 @@ export function MissionForm() {
...
         missionId,
         mission.draft.actions,
         originalMissionWithActionsRef.current?.actions
       )
 
-      await Promise.all(
-        missionActionDatas.map(async missionActionData => {
+      await Promise.all([
+        ...deletedMissionActionIds.map(async missionActionId => {
+          await deletedMissionAction(missionActionId)
```
Comment (louptheron) [inline frontend/src/features/SideWindow/MissionForm/index.tsx:133]: deletedMissionAction -> deleteMissionAction

**Review by louptheron — COMMENTED** [review]
Note pour moi-même.
Reste à faire : blocage sans `vessel_id` dans le `backend` et la `db`
