### PR TITLE
Fix show base layer radio button

### LINKED ISSUE #1439: Le changement de fonds de carte est parfois bloqué et demande un rechargement de l'appli
Remonté par Yves, apparaitrait après un certain temps d'utilisation et / ou après plusieurs changements de fonds

### PR DESCRIPTION
**Pull request by louptheron**
## Linked issues

- Resolve #1439 

----

- [ ] Tests E2E (Cypress)

### CODE REVIEW

File: frontend/src/features/layers/base/BaseLayerList.tsx [hunk 1]
```diff
@@ -0,0 +1,93 @@
...
+`
+
+const List = styled.ul<{
+  isShowed: boolean
+  layersLength: number
+}>`
+  margin: 0;
+  border-radius: 0;
+  padding: 0;
+  height: ${p => (p.isShowed && p.layersLength ? 37 * p.layersLength : 0)}px;
```
Comment (ivangabriele) [inline frontend/src/features/layers/base/BaseLayerList.tsx:86]: It would too much time to change it in this PR but maybe we'll need a cleaner CSS-based solution (for the `37 * ...`).

File: frontend/src/features/layers/base/BaseLayerList.tsx [hunk 2]
```diff
@@ -0,0 +1,93 @@
...
+  padding-left: 20px;
+  user-select: none;
+  border-top-left-radius: 2px;
+  border-top-right-radius: 2px;
+  border-bottom-left-radius: ${p => (p.isShowed ? '0' : '2px')};
+  border-bottom-right-radius: ${p => (p.isShowed ? '0' : '2px')};
+`
+
+const List = styled.ul<{
+  isShowed: boolean
```
Comment (ivangabriele) [inline frontend/src/features/layers/base/BaseLayerList.tsx:80]: Why not just a `&&` in the JSX?

File: frontend/src/features/layers/base/BaseLayerRow.tsx [hunk 3]
```diff
@@ -0,0 +1,38 @@
...
+  cursor: pointer;
+  background: ${COLORS.background};
+  color: ${COLORS.gunMetal};
+  border-bottom: 1px solid ${COLORS.lightGray};
+  display: block;
+  line-height: 18px;
+  user-select: none;
+
+  :hover {
+    background: ${COLORS.shadowBlueLittleOpacity};
```
Comment (ivangabriele) [inline frontend/src/features/layers/base/BaseLayerRow.tsx:36]: `shadowBlueLittleOpacity` is not part of official colors anymore I think.

File: frontend/src/domain/entities/layers/constants.ts [hunk 4]
```diff
@@ -1,52 +1,41 @@
...
+  REGULATORY: 'REGULATORY',
+  VESSEL: 'VESSEL',
+  VESSEL_ALERT: 'VESSEL_ALERT',
+  VESSEL_ALERT_AND_BEACON_MALFUNCTION: 'VESSEL_ALERT_AND_BEACON_MALFUNCTION',
+  VESSEL_BEACON_MALFUNCTION: 'VESSEL_BEACON_MALFUNCTION'
 }
 
-const Layers = {
+/* eslint-disable sort-keys-fix/sort-keys-fix */
+export const Layers = {
```
Comment (ivangabriele) [inline frontend/src/domain/entities/layers/constants.ts:38]: I would avoid the plural here ^^.

File: frontend/src/features/map/overlays/TrackTypeCardOverlay.js [hunk 5]
```diff
@@ -34,7 +34,7 @@ const TrackTypeCardOverlay = ({ map, pointerMoveEventPixel, feature }) => {
 
   useEffect(() => {
     if (overlayRef.current && overlayObjectRef.current) {
```
Comment (ivangabriele) [inline frontend/src/features/map/overlays/TrackTypeCardOverlay.js:36]: That's a hell lot of ifs and nullish checks, not the goal of this PR but maybe a TODO?

File: frontend/src/features/map/overlays/VesselTrackCardOverlay.js [hunk 6]
```diff
@@ -44,7 +44,7 @@ const VesselTrackCardOverlay = ({ map, feature }) => {
 
   useEffect(() => {
     if (overlayRef.current && overlayObjectRef.current) {
```
Comment (ivangabriele) [inline frontend/src/features/map/overlays/VesselTrackCardOverlay.js:46]: Same thing here (it's almost the same code as `frontend/src/features/map/overlays/TrackTypeCardOverlay.js:36`).

**Review by ivangabriele — APPROVED** [review]

File: frontend/src/features/layers/base/BaseLayerList.tsx (hunk 1 above)
Comment (louptheron) [reply frontend/src/features/layers/base/BaseLayerList.tsx:86]: If you have an idea of something simple to trigger a `transition` to the final `height`, otherwise let's do it in another PR indeed.

File: frontend/src/features/layers/base/BaseLayerList.tsx (hunk 2 above)
Comment (louptheron) [reply frontend/src/features/layers/base/BaseLayerList.tsx:80]: Because we need the `transition`

File: frontend/src/features/layers/base/BaseLayerRow.tsx (hunk 3 above)
Comment (louptheron) [reply frontend/src/features/layers/base/BaseLayerRow.tsx:36]: Indeed, but we need a global rework of the map layers box : regulations, administratives and base layers. As all colors but also icons, margins, etc. changed.
I propose to share the components of Env in the UI and reuse them in Fish.
