### PR TITLE
Performance fixes and reportings features

### LINKED ISSUE #1373: Signalements - Ajouter l'émetteur (le trigramme) aussi quand l'origine est un OPS ou un SIP
Mettre "émetteur : XXX" en-dessous de la description

### LINKED ISSUE #1702: [Signalements] Ajouter l'émetteur quand l'origine est une unité externe

### PR DESCRIPTION
**Pull request by louptheron**
[Description]

## Linked issues

- Convert APIWorker to typescript and remove duplicate calls to all APIs
- Resolve #1373
- Resolve #1702 

----

- [ ] Tests E2E (Cypress)

### CODE REVIEW

File: frontend/src/api/APIWorker.tsx [hunk 1]
```diff
@@ -1,83 +1,79 @@
...
 import getAllBeaconMalfunctions from '../domain/use_cases/beaconMalfunction/getAllBeaconMalfunctions'
-import { openBeaconMalfunctionInKanban } from '../domain/use_cases/beaconMalfunction/openBeaconMalfunctionInKanban'
 import getVesselBeaconMalfunctions from '../domain/use_cases/beaconMalfunction/getVesselBeaconMalfunctions'
-import getAllSpecies from '../domain/use_cases/species/getAllSpecies'
-import getVesselReportings from '../domain/use_cases/vessel/getVesselReportings'
-import { getSilencedAlerts } from '../domain/use_cases/alert/getSilencedAlerts'
-import getFishingInfractions from '../domain/use_cases/infraction/getFishingInfractions'
+import { openBeaconMalfunctionInKanban } from '../domain/use_cases/beaconMalfunction/openBeaconMalfunctionInKanban'
 import getAllControllers from '../domain/use_cases/controller/getAllControllers'
+import { getAllFleetSegments } from '../domain/use_cases/fleetSegment/getAllFleetSegments'
```
Comment (ivangabriele) [inline frontend/src/api/APIWorker.tsx:11]: To avoid these endless lists of imports, I find it's more readable to "index" all the actions in [this file](https://github.com/MTES-MCT/monitorfish/blob/master/frontend/src/domain/actions.ts).

It's not ideal to do that in general because I think (I need to check that) it doesn't allow the detection of unused code. We don't do it yet but will surely do it once all the files have been migrated to TS. However in the case of Redux actions, I think it's an acceptable tradeoff since there are easy to recheck manually.

It's also a nice way to start namespacing which shorten the name of Redux actions (both reducers and dispatcher) without having to repeat the name of the entity in te name of the function, i.e.:

`vesselActions.updateTracks()` instead of `updateVesselTracks()`

File: frontend/src/api/APIWorker.tsx [hunk 2]
```diff
@@ -1,83 +1,79 @@
 import { useEffect, useRef, useState } from 'react'
```
Comment (ivangabriele) [inline frontend/src/api/APIWorker.tsx:1]: I know it's a refactoring, I think this should just be a pure function or maybe a class, no need for React here (especially if it's used as a webworker). And this is the power of Redux (vs `useReducer`), you can access it outside of functions (and dispatch its actions).

Maybe add a TODO for later on?

File: frontend/src/features/VesselSidebar/Reportings/index.tsx [hunk 3]
```diff
@@ -0,0 +1,90 @@
...
+  const [reportingTab, setReportingTab] = useState(ReportingTab.CURRENT_REPORTING)
+  const previousSelectedVesselIdentity = usePrevious(selectedVesselIdentity)
+
+  useEffect(() => {
+    if (!archivedReportingsFromDate) {
+      return
+    }
+
+    dispatch(getVesselReportings())
+    if (!vesselsAreEquals(previousSelectedVesselIdentity, selectedVesselIdentity)) {
```
Comment (ivangabriele) [inline frontend/src/features/VesselSidebar/Reportings/index.tsx:35]: That's better to use a `useMemo()` to have only the the data fetching inside this `useEffect()`, especially since it's a setState.

File: frontend/src/features/VesselSidebar/Tabs.tsx [hunk 4]
```diff
@@ -0,0 +1,149 @@
...
+
+export function Tabs() {
+  const dispatch = useMainAppDispatch()
+  const { selectedVessel, vesselSidebarTab } = useMainAppSelector(state => state.vessel)
+  const isAdmin = useMainAppSelector(state => state.global.isAdmin)
+
+  return (
+    <TabList>
+      {isAdmin && (
+        <Tab
```
Comment (ivangabriele) [inline frontend/src/features/VesselSidebar/Tabs.tsx:23]: We have the icons both as clean React components and as `IconButton` in Monitor UI.

If some icons are missing, it's easy to add them (just [run](https://github.com/MTES-MCT/monitor-ui/blob/main/package.json#L22) `yarn build:icons` once the [src/assets/icons](https://github.com/MTES-MCT/monitor-ui/tree/main/src/assets/icons) folder is updated.

**Review by ivangabriele — APPROVED** [review]
Nice PR :).

File: frontend/src/features/VesselSidebar/Reportings/index.tsx (hunk 3 above)
Comment (louptheron) [reply frontend/src/features/VesselSidebar/Reportings/index.tsx:35]: Do you mean to replace the `reportingState` by a `useMemo` ?
But there is a `onClick` below : 
```
onClick={() => setReportingTab(ReportingTab.CURRENT_REPORTING)}
```

File: frontend/src/features/VesselSidebar/Tabs.tsx (hunk 4 above)
Comment (louptheron) [reply frontend/src/features/VesselSidebar/Tabs.tsx:23]: I added a TODO
