### PR TITLE
Mission - Correction de bugs et amélioration de la sauvegarde en auto-save

### LINKED ISSUE #2698: Missions - Enregistrement automatique
- Enregistrement à chaque modification du formulaire (mission & actions)
- Affichage de la date de création de la mission dans le bandeau du bas

### PR DESCRIPTION
**Pull request by louptheron**
## Linked issues

- Resolve #2698
- Evite l'enregistrement de la mission à chaque modification d'une action de mission
- Sors les actions d'update du formulaire dans redux thunk
- Corrige l'invalidation des tags rtk

----

- [x] Tests E2E (Cypress)

## Summary by CodeRabbit

- **New Features**
	- Introduced auto-saving functionality for missions and mission actions.
	- Added validation for mission and mission action form values.
	- Implemented a feature to check if mission event data is outdated and reset it accordingly.
	- Enhanced mission form with the ability to handle unsynchronized properties and prevent redundant form submissions.
- **Bug Fixes**
	- Fixed an issue with mission action creation logic to correctly return the updated action.
	- Corrected event listening toggles to accurately reflect the state of event listening.
- **Refactor**
	- Simplified logic for listening to mission event updates.
	- Optimized mission and mission action saving processes.
	- Improved form value handling and validation checks.
- **Tests**
	- Updated Cypress E2E tests to align with new API responses and added additional configuration for testing auto-save functionality.
- **Chores**
	- Updated import paths for better consistency and maintainability.

### CODE REVIEW

File: frontend/src/features/Mission/components/MissionForm/utils.tsx [hunk 1]
```diff
@@ -61,6 +42,34 @@ export function getMissionActionsDataFromMissionActionsFormValues(
...
+  originalMissionActions: MissionAction.MissionAction[] = [],
+  index?: number
+) {
+  const missionActionFormValuesWithAllProps = {
+    ...MISSION_ACTION_FORM_VALUES_SKELETON,
+    ...missionActionFormValues
+  }
+
+  const maybeValidMissionActionData = omit(missionActionFormValuesWithAllProps, [
+    'isDraft',
```
Comment (ivangabriele) [inline frontend/src/features/Mission/components/MissionForm/utils.tsx:57]: La prop `isDraft` ne sert plus à rien je pense, si ?

File: frontend/src/features/Mission/components/MissionForm/index.tsx [hunk 2]
```diff
@@ -391,81 +483,96 @@ export function MissionForm() {
...
 
         return
       }
 
-      createOrUpdate({
-        actionsFormValues: nextActionsFormValues,
-        mainFormValues
-      })
+      const createdId = await autoSaveAction(actionCopy)
+      if (!createdId) {
```
Comment (ivangabriele) [inline frontend/src/features/Mission/components/MissionForm/index.tsx:564]: Un duplicate c'est forcément une création non ?

File: frontend/src/features/Mission/components/MissionForm/index.tsx [hunk 3]
```diff
@@ -229,6 +233,85 @@ export function MissionForm() {
     ]
   )
 
+  const autoSaveAction = useCallback(
```
Comment (ivangabriele) [inline frontend/src/features/Mission/components/MissionForm/index.tsx:236]: `createMissionActionIfNotExist` ?

File: frontend/src/features/Mission/components/MissionForm/index.tsx [hunk 4]
```diff
@@ -306,32 +389,41 @@ export function MissionForm() {
...
         dispatch(missionFormActions.setIsDraftDirty(true))
 
         return
       }
 
-      createOrUpdate({
-        actionsFormValues: nextActionFormValuesOrActions,
-        mainFormValues
-      })
+      const createdId = await autoSaveAction(nextActionFormValues)
```
Comment (ivangabriele) [inline frontend/src/features/Mission/components/MissionForm/index.tsx]: `maybeNewMissionActionId` ?

**Review by ivangabriele — APPROVED** [review]

**Comment by ivangabriele** [comment]
J'ai oublié de mettre mon com :

Plus propre comme ça en effet ^^. J'aurais peut-être sorti les fonctions `autoSave*` en bonus comme rabbit le dit mais pas très important sur cette PR.
