### PR TITLE
Add ORGP REG to backoffice and fix fishing period resume

### LINKED ISSUE #1428: Réglementation – Ajouter un type de reg "Reg. ORGP" et les ensembles reg correspondants
Vu avec Diane, elle doit de plus en plus rentrer les réglementations des ORGP pour l'outre-mer. 

Il faudrait donc un nouveau type de reg dans le backoffice que s'appellerio "Reg. ORGP" (au même niveau que Reg. France ou Reg. UE). Et au sein de ce nouveau type de reg, il y aurait ces ensembles réglementaires qui correspondent aux différentes ORGP : 
- CCAMLR
- CTOI / IOTC
- ICCAT / CICTA
- NEAFC / CPANE
- OPANO / NAFO
- SIOFA / APSOI

### LINKED ISSUE #1466: Quand on rentre un remarque dans le champ Période du Backoffice (sans période), le champ ne s'affiche pas dans le résumé réglementaire
Ex: Manche Est - Pétoncle blanc - Secteur Est Baie de Seine

### PR DESCRIPTION
**Pull request by louptheron**
[Description]

## Linked issues

- Resolve #1428
- Resolve #1466

----

- [ ] Tests E2E (Cypress)

### CODE REVIEW

File: frontend/src/domain/entities/regulatory.js [hunk 1]
```diff
@@ -177,6 +177,7 @@ export const FRANCE = 'Réglementation France'
 export const UE = 'Réglementation UE'
```
Comment (ivangabriele) [inline frontend/src/domain/entities/regulatory.js:177]: Why not gather these labels into named objects like `REGULATION_COUNTRY_LABEL`, `REGULATION_ZONE_LABEL`, etc, since they are related? Single string global constants are usually quite seldom.

**Review by ivangabriele — APPROVED** [review]

File: frontend/src/domain/entities/regulatory.js (hunk 1 above)
Comment (louptheron) [reply frontend/src/domain/entities/regulatory.js:177]: This will need plenty of changes in backoffice and other part of the app, I prefer not to refactor that in this PR
